from typing import Dict

from toolbox.constants.summary_constants import PS_DATA_FLOW_TITLE, PS_ENTITIES_TITLE, PS_FEATURE_TITLE, PS_OVERVIEW_TITLE, \
    PS_SUBSYSTEM_TITLE
from toolbox.llm.prompts.prompt import Prompt
from toolbox.summarize.prompts.project_summary_prompts import DATA_FLOW_SECTION_PROMPT, ENTITIES_SECTION_PROMPT, \
    FEATURE_SECTION_PROMPT, \
    OVERVIEW_SECTION_PROMPT, SUBSYSTEM_SECTION_PROMPT

PROJECT_SUMMARY_MAP: Dict[str, Prompt] = {
    PS_OVERVIEW_TITLE: OVERVIEW_SECTION_PROMPT,
    PS_FEATURE_TITLE: FEATURE_SECTION_PROMPT,
    PS_ENTITIES_TITLE: ENTITIES_SECTION_PROMPT,
    PS_SUBSYSTEM_TITLE: SUBSYSTEM_SECTION_PROMPT,
    PS_DATA_FLOW_TITLE: DATA_FLOW_SECTION_PROMPT
}
