DEFAULT_PARENT_PRIMARY_THRESHOLD = 0.80  # The minimum percentile to consider a candidate as true
DEFAULT_PARENT_SECONDARY_THRESHOLD = 0.60
DEFAULT_PARENT_MIN_THRESHOLD = 0.4  # The minimum percentile allowed for a top parent prediction.
DEFAULT_MIN_RANKING_SCORE = 0.5
DEFAULT_MAX_N_CHILDREN = 50
DEFAULT_SORTING_ALGORITHM = "transformer"

GENERATE_EXPLANATIONS_DEFAULT = False
PROJECT_SUMMARY_HEADER = "Software Specification"
DEFAULT_LINKS_TAG = "links"
DEFAULT_RANKING_MODEL = "claude-2.0"
DEFAULT_SEARCH_FILTER = 50
SEARCH_PARENT_TYPE = "prompt"
SEARCH_CHILD_TYPE = "artifacts"

DEFAULT_LINK_THRESHOLD = 0.6
DEFAULT_SCALED_THRESHOLD = 0.7
FIRST_PASS_THRESHOLD_DELTA = 0.2
DEFAULT_SELECT_TOP_PREDICTIONS = True
DEFAULT_MAX_CONTEXT_ARTIFACTS = None
RANKING_MIN_SCORE = 0
RANKING_MAX_SCORE = 5
DEFAULT_SCORE = 0  # TODO: Rename to DEFAULT_RANKING_SCORE when refactor is done.
DEFAULT_EXPLANATION_SCORE_WEIGHT = 0.25
DEFAULT_EMBEDDINGS_SCORE_WEIGHT = 0.75
PRE_SORTED_SCORE = 0.99
CLUSTERING_LINK_THRESHOLD = 0.1
"""
Tags
"""
RANKING_PARENT_TAG = "parent-artifact"
RANKING_ARTIFACT_TAG = "artifact-answers"
RANKING_PARENT_SUMMARY_TAG = "parent-summary"
SUB_SYSTEMS_TAG = "sub-systems"
ENTITIES_TAG = "entities"
DERIVATION_TAG = "derivation"
JUSTIFICATION_TAG = "justification"
CHANGE_IMPACT_TAG = "change-impact"
FUNCTIONALITY_TAG = "functionality"

RANKING_ID_TAG = "id"
RANKING_EXPLANATION_TAG = "explanation"
RANKING_SCORE_TAG = "score"
