"""
Sections
"""
PS_OVERVIEW_TITLE = "Overview"
PS_OVERVIEW_TAG = "overview"

PS_FEATURE_TITLE = "Features"
PS_FEATURE_TAG = "feature"

PS_ENTITIES_TITLE = "Entities"
PS_ENTITIES_TAG = "entity"

PS_SUBSYSTEM_TITLE = "Sub-systems"
PS_SUBSYSTEM_TAG = "sub-system"

PS_DATA_FLOW_TITLE = "Data Flow"
PS_DATA_FLOW_TAG = "data-flow"

PS_QUESTIONS_HEADER = "\n\n# Questions\n"

PS_FILE_NAME = "project_summary.txt"
PS_STATE_FILE_NAME = "project_summary_state.json"

CUSTOM_TITLE_TAG = "title"

"""
Defaults 
"""
PS_NOTES_TAG = "notes"
PS_DEFAULT_SAVE_PROGRESS = True
MAX_TOKENS_FOR_PROJECT_SUMMARY = 60000
MAX_ITERATIONS_ALLOWED = 5
MAX_NL_SIZE_BEFORE_SUMMARIZATION = 60_000
"""
Mappings
"""
DEFAULT_PROJECT_SUMMARY_SECTIONS = [
    PS_FEATURE_TITLE,
    PS_ENTITIES_TITLE,
    PS_SUBSYSTEM_TITLE,
    PS_DATA_FLOW_TITLE,
    PS_OVERVIEW_TITLE
]

DEFAULT_PROJECT_SUMMARY_SECTIONS_DISPLAY_ORDER = [
    PS_OVERVIEW_TITLE,
    PS_FEATURE_TITLE,
    PS_ENTITIES_TITLE,
    PS_SUBSYSTEM_TITLE,
    PS_DATA_FLOW_TITLE
]

PROJECT_SUMMARY_TAGS = {
    PS_OVERVIEW_TITLE: PS_OVERVIEW_TAG,
    PS_FEATURE_TITLE: PS_FEATURE_TAG,
    PS_ENTITIES_TITLE: PS_ENTITIES_TAG,
    PS_SUBSYSTEM_TITLE: PS_SUBSYSTEM_TAG,
    PS_DATA_FLOW_TITLE: PS_DATA_FLOW_TAG
}
SPECIAL_TAGS_ITEMS = {PS_SUBSYSTEM_TITLE, PS_ENTITIES_TITLE}
MULTI_LINE_ITEMS = {PS_SUBSYSTEM_TITLE}
USE_PROJECT_SUMMARY_SECTIONS = {PS_OVERVIEW_TITLE}

ARTIFACT_HEADER = "Software Artifacts"
VERSION_HEADER = "Section Versions"
BODY_ARTIFACT_TITLE = f"# {ARTIFACT_HEADER}\nBelow are the artifact of the software system."
BODY_VERSION_TITLE = f"# {VERSION_HEADER}\nBelow are the section versions for the software system."
